src/monument/urls.py
from django.urls import path
from monument.views import create_monument_view,detail_monument_view, edit_monument_view, delete_monument_view, saved_monument_view, get_monument_queryset, unsave_monument

app_name='monument'

urlpatterns = [
	path('create/',create_monument_view, name="create"),
	path('<slug>/',detail_monument_view, name="detail"),
	path('<slug>/edit',edit_monument_view, name="edit"),
	path('<slug>/delete',delete_monument_view, name="delete"),
	path('<slug>/save', saved_monument_view, name="saving"),
	 path('<slug>/unsave/',unsave_monument,name="unsave"),

]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from principal.views import *
from account.views import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', home_screen_view, name="home"),
    path('register/',registration_view,name="register"),
    path('logout/',logout_view,name="logout"),
    path('login/',login_view,name="login"),
    path('account/',account_view,name="account"),
    path('account/edit/',account_edit,name="edit"),
    path('account/saved/',account_saved,name="saved"),
    path('account/aboutus/',about_us_view,name="AboutUs"),
    path('monument/',include('monument.urls','monument')),
    path('routing/', include('routing.urls', namespace='routing')),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('must_admin/', must_admin_view, name="must_admin"),
    path('account/dashboard/', users_table_view, name="dashboard"),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/routing/urls.py
from django.urls import path
from routing.views import home

app_name = 'routing'

urlpatterns = [
    path('calculator/', home, name='homepage'),
]

src/templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>


<div class="d-flex flex-row align-items-center footer bg-white border-top shadow-lg ">
	<p class="m-auto" style="color:gray;"> Ensaf PFA &#8642; 2022 &#8643; </p>	
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

src/templates/snippets/header.html
{% load static %}

<!-- bootstrap -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style type="text/css">
	@media (min-width: 768px) {
  html {
    font-size: 16px;
  }
	}

	.container {
	  max-width: 960px;
	}

	.pricing-header {
	  max-width: 700px;
	}

	.card-deck .card {
	  min-width: 220px;
	}

	.search-bar{
		max-width: 500px;
		width: 100%;
	}

	form{
		width: 100%;
	}

</style>

<!-- Header Elements -->

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-info border-bottom shadow-sm">
	<h5 class="my-0 mr-md-auto font-weight-normal">
      <a class="p-2 text-white" href="{% url 'home' %}"><i style="font-size:20px" class="fa fa-home"></i> Acceuil </a> 
    </h5>


	  <div class="search-bar mt-1 mr-2">
	  	<form method="get">
	  		<input class="form-control"  type="text" name="q" id="id_q" placeholder="Search...">
	  	</form>
	  </div>
  <nav class="my-2 my-md-0 mr-md-3">  
  	{% if request.user.is_authenticated %} 
    <a class="p-2 text-white" href="{% url 'routing:homepage' %}"><i style="font-size:16px" class="fa fa-map-o"></i> Routing </a>
    {% if request.user.is_admin %}
    <a class="p-2 text-white" href="{% url 'monument:create' %}"><i style="font-size:16px" class="fa fa-plus-circle"></i> Add Monument</a> 
    <a class="p-2 text-white" href="{% url 'dashboard' %}"><i style="font-size:16px" class="fa fa-table"></i> Dashboard </a> 
    {% endif %}

    
		<a class="p-2 text-white" href="{% url 'account' %}"><i style="font-size:16px" class="fa fa-user-circle-o"></i> Account</a> 
		<a class="p-2 text-white" href="{% url 'logout' %}"><i style="font-size:16px" class="fa">&#xf08b;</i> Logout </a>
		{% else %}
		<a class="p-2 text-white" href="{% url 'login' %}"><i style="font-size:16px" class="fa">&#xf08b;</i> Login</a> 
		<a class="p-2 text-white" href="{% url 'register' %}"><i style="font-size:16px" class="fa fa-pencil"></i> Register</a>
		{% endif %}
  </nav>
</div>

<script type="text/javascript">
	document.getElementById("id_q").value = "{{query}}"
</script>