src/monument/urls.py
from django.urls import path
from monument.views import create_monument_view,detail_monument_view, edit_monument_view, delete_monument_view, saved_monument_view, get_monument_queryset, unsave_monument

app_name='monument'

urlpatterns = [
	path('create/',create_monument_view, name="create"),
	path('<slug>/',detail_monument_view, name="detail"),
	path('<slug>/edit',edit_monument_view, name="edit"),
	path('<slug>/delete',delete_monument_view, name="delete"),
	path('<slug>/save', saved_monument_view, name="saving"),
	 path('<slug>/unsave/',unsave_monument,name="unsave"),

]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from principal.views import *
from account.views import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', home_screen_view, name="home"),
    path('register/',registration_view,name="register"),
    path('logout/',logout_view,name="logout"),
    path('login/',login_view,name="login"),
    path('account/',account_view,name="account"),
    path('account/edit/',account_edit,name="edit"),
    path('account/saved/',account_saved,name="saved"),
    path('account/aboutus/',about_us_view,name="AboutUs"),
    path('monument/',include('monument.urls','monument')),
    path('routing/', include('routing.urls', namespace='routing')),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('must_admin/', must_admin_view, name="must_admin"),
    path('account/dashboard/', users_table_view, name="dashboard"),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/monument/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver
from account.models import Account

def upload_location(instance, filename, **kwargs):
	file_path = 'monument/{title}-{filename}'.format(
				title=str(instance.title), filename=filename)
	return file_path

class Monument(models.Model):
	#attributes
	title 					= models.CharField(max_length=50, null=False, blank=False)
	description 			= models.TextField(max_length=10000, null=False, blank=False)
	image		 			= models.ImageField(upload_to=upload_location, null=True, blank=True)
	year					= models.CharField(max_length=50, null=False, blank=True)
	latitude				= models.FloatField(null=False, blank=True, default=0)
	longitude				= models.FloatField(null=False, blank=True, default=0)
	city					= models.CharField(max_length=50, null=True, blank=True, default="Casablanca")

	#to generate custom links for each monument
	slug 					= models.SlugField(blank=True, unique=True)

	#for the "saved" feature
	saved = models.ManyToManyField(Account, default=None, blank=True)

	def __str__(self):
		return self.title

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url 



@receiver(post_delete, sender=Monument)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 


def pre_save_monument_receiver(sender, instance, *args,**kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.title)

pre_save.connect(pre_save_monument_receiver, sender=Monument)

src/monument/forms.py
from django import forms
from monument.models import Monument

class AddMonumentForm(forms.ModelForm):

	class Meta:
		model = Monument
		fields = ['title','year', 'description', 'image','latitude','longitude','city']

class UpdateMonumentForm(forms.ModelForm):

	class Meta:
		model = Monument
		fields = ['title','year', 'description', 'image','city']

	def save(self, commit=True):
		monument = self.instance
		monument.title = self.cleaned_data['title']
		monument.year = self.cleaned_data['year']
		monument.description = self.cleaned_data['description']

		if self.cleaned_data['image']:
			monument.image = self.cleaned_data['image']

		if commit:
			monument.save()
		return monument

src/monument/views.py
from django.shortcuts import render, get_object_or_404, redirect
from monument.models import Monument
from monument.forms import AddMonumentForm, UpdateMonumentForm
from django.db.models import Q
from django.http import HttpResponse
from django.http import HttpResponseRedirect
import folium
from geopy.geocoders import Nominatim
from geopy.distance import geodesic

# Create your views here.

def create_monument_view(request):
	context = {}
	user = request.user
	if not user.is_authenticated or not user.is_admin:
		return redirect("must_admin")

	form = AddMonumentForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		obj.save()
		form = AddMonumentForm()
		return redirect("home")

	context['form'] = form

	return render(request,"monument/create_monument.html",context)


def detail_monument_view(request, slug):
	context={}
	user = request.user
	isSaved = False
	
	monument = get_object_or_404(Monument, slug=slug)
	if monument.saved.filter(id= request.user.id).exists():
		isSaved = True

	# folium map
	latitude = monument.latitude
	longitude = monument.longitude
	pointA = (latitude,longitude)
	tooltip = monument.title
	m = folium.Map(width=600,height=400,location=pointA, zoom_start=14)
	folium.Marker([latitude,longitude],tooltip=tooltip,icon=folium.Icon(color='red',icon='cloud')).add_to(m)
	m = m._repr_html_()

	context['monument'] = monument
	context['user'] = user
	context['map'] = m
	context['isSaved'] = isSaved

	return render(request,"monument/detail_monument.html",context)

def edit_monument_view(request, slug):

	context = {}

	user = request.user
	if not user.is_authenticated or not user.is_admin:
		return redirect("must_admin")

	monument = get_object_or_404(Monument, slug=slug)

	if request.POST:
		form = UpdateMonumentForm(request.POST or None, request.FILES or None, instance=monument)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Changements enregistrés"
			monument = obj

	form = UpdateMonumentForm(
			initial = {
					"title": monument.title,
					"description": monument.description,
					"image": monument.image,
					"year":monument.year,
					"city":monument.city,
			}
		)

	context['monument'] = monument
	context['form'] = form
	return render(request,"monument/edit_monument.html",context)



def delete_monument_view(request, slug):
	context={}

	user = request.user
	if not user.is_authenticated or not user.is_admin:
		return redirect("must_admin")

	monument = get_object_or_404(Monument, slug=slug)
	context['monument'] = monument

	if request.method == "POST" : 
		monument.delete()
		return redirect("home")

	return render(request,"monument/delete_monument.html",context)


#function to save/unsave monuments from inside monument details
def saved_monument_view(request, slug):
	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	monument = get_object_or_404(Monument, slug=slug)
	if monument.saved.filter(id= request.user.id).exists():
		monument.saved.remove(request.user)
	else:
		monument.saved.add(request.user)

	return HttpResponseRedirect(request.META['HTTP_REFERER'])




def get_monument_queryset(query=None):
	queryset = []
	queries = query.split(" ")
	for q in queries:
		monuments = Monument.objects.filter(
				Q(title__icontains=q) | 
				Q(year__icontains=q) |
				Q(city__icontains=q)
			).distinct()

		for monument in monuments:
			queryset.append(monument)

	return list(set(queryset))


#function to unsave monuments inside saved list:
def unsave_monument(request, slug):

	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	monument = get_object_or_404(Monument, slug=slug)
	if monument.saved.filter(id= request.user.id).exists():
		monument.saved.remove(request.user)

	return HttpResponseRedirect(request.META['HTTP_REFERER'])

src/monument/templates/monument/create_monument.html
{% extends 'base.html' %}

{% load static %}

{% block content%}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<div class="d-flex flex-column pb-3">
    			<img class="img-fluid mx-auto d-block" src="{% static 'logo.png' %}" height="250" width="250">
  			</div>

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Nom du monument :</label>
					<input class="form-control" type="text" name="title" id="id_title" required autofocus>
				</div>

				<div class="form-group">
					<label for="id_year">Date de construction :</label>
					<input class="form-control" type="string" name="year" id="id_year" placeholder="" required autofocus>
				</div>

				<div class="form-group">
					<label for="id_year"> Ville :</label>
					<input class="form-control" type="string" name="city" id="id_city" placeholder="" required autofocus>
				</div>

				<!-- Description -->
				<div class="form-group">
					<label for="id_body">Description</label>
					<textarea class="form-control" rows="10" type="text" name="description" id="id_body" required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label for="id_image">Image</label><br>
					<input  type="file" name="image" id="id_image" accept="image/*" required>
				</div>

				<!-- Latitude -->
				<div class="form-group">
					<label for="id_latitude">Latitude</label>
					<input class="form-control" type="float" name="latitude" id="id_title" required autofocus>
				</div>

				<!-- Longitude -->
				<div class="form-group">
					<label for="id_longitude">Longitude</label>
					<input class="form-control" type="float" name="longitude" id="longitude" required autofocus>
				</div>

				<!-- Submit btn -->
				{% for field in form %}
				  <p>
				    {% for error in field.errors %}
				      <p style="color: red">{{ error }}</p>
				    {% endfor %}
				  </p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
					  <p>{{form.non_field_errors}}</p>
					</div>  
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-info btn-block m-auto" type="submit"> Ajouter Monument </button>
			</form>	
		</div>
	</div>
</div>

{% endblock content %}

src/monument/templates/monument/delete_monument.html
{% extends 'base.html' %}

{% load static %}

{% block content%}

{% include 'account/snippets/style.html' %}

<div class="container" >
	<div class="d-flex flex-column pb-3">
		<br>
		<br>
		<br>
    	<img class="img-fluid mx-auto d-block" src="{% static 'logo.png' %}" height="250" width="250">
    	<br>
    	<p class="m-auto">Are you sure you want to delete the monument: {{monument}} ? </p>  
    	<br>
    	  	<form method="POST" class="form-signin">{% csrf_token %}
    		<a class="btn btn-secondary" href="{% url 'home' %}"> Cancel </a>
			<button class="btn btn-danger" type="submit" style="display: inline-block; margin-left: 100px;" onclick="deleted()">Confirm</button>
    	</form>  	
  	</div>

</div>

<script type="text/javascript">
	function deleted(){
 	 alert("Monument was deleted! ");
	}
</script>


{% endblock content%}

src/monument/templates/monument/detail_monument.html
{% extends 'base.html' %}

{% load static %}

{% block content%}

<style type="text/css">
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">
		  {% if success_message %}
		  <p style="color:green; text-align: center;">{{ success_message }}</p>
		  {% endif %}

		<!-- Blog Post -->
		<div class="card m-auto">
			<img class="card-img-top" src="{{monument.imageURL}}" style="width:100%; height: 100%;">
			<div class="card-body mt-2 mb-2">
			  <h2 class="card-title">{{monument.title}}</h2>
			  <h6 class="card-title"> City:  {{monument.city}}</h6>
			  <p class="card-text">{{monument.description|safe}}</p>

			  {{ map|safe}}

			</div>
			<div class="card-footer text-muted">
			  Date de construction : {{monument.year}}
			  	{% if user.is_authenticated %}
			  		{% if isSaved %}
						<a class="btn btn-outline-info" style="display: inline-block; float: right; margin: auto;" href="{% url 'monument:saving' monument.slug %}">Unsave</a>
			  		{% else %}
						<a class="btn btn-outline-info" style="display: inline-block; float: right; margin: auto;" href="{% url 'monument:saving' monument.slug %}">save</a>
					{% endif %}
				{% endif %}
			</div>
			

		</div>
	</div>
</div>


{% endblock content %}

src/monument/templates/monument/edit_monument.html
{% extends 'base.html' %}

{% load static %}

{% block content%}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

  	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<div class="d-flex flex-column pb-3">
    			<img class="img-fluid mx-auto d-block" src="{% static 'logo.png' %}" height="250" width="250">
  				</div>
  				<div class="form-group">
					{% if success_message %}
					<h6 style="color:green; text-align: center;">{{success_message}}</h3>
					{% endif %}
				</div>
				<!-- title -->
				<div class="form-group">
					<label for="id_title">Nom du monument :</label>
					<input class="form-control" type="text" name="title" value="{{form.initial.title}}" required autofocus>
				</div>

				<div class="form-group">
					<label for="id_year">Date de construction :</label>
					<input class="form-control" type="string" name="year" id="id_year" value={{form.initial.year}} required autofocus>
				</div>

				<div class="form-group">
					<label for="id_year"> Ville :</label>
					<input class="form-control" type="string" name="city" id="id_city" value={{form.initial.city}} required autofocus>
				</div>

				<!-- Description -->
				<div class="form-group">
					<label for="id_body">Description</label>
					<textarea class="form-control" rows="10" type="text" name="description" id="id_body" required> {{form.initial.description}} </textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">

				<!-- Submit btn -->
				{% for field in form %}
				  <p>
				    {% for error in field.errors %}
				      <p style="color: red">{{ error }}</p>
				    {% endfor %}
				  </p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
					  <p>{{form.non_field_errors}}</p>
					</div>  
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-info btn-block m-auto" type="submit"> Enregistrer </button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}