src/monument/urls.py
from django.urls import path
from monument.views import create_monument_view,detail_monument_view, edit_monument_view, delete_monument_view, saved_monument_view, get_monument_queryset, unsave_monument

app_name='monument'

urlpatterns = [
	path('create/',create_monument_view, name="create"),
	path('<slug>/',detail_monument_view, name="detail"),
	path('<slug>/edit',edit_monument_view, name="edit"),
	path('<slug>/delete',delete_monument_view, name="delete"),
	path('<slug>/save', saved_monument_view, name="saving"),
	 path('<slug>/unsave/',unsave_monument,name="unsave"),

]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from principal.views import *
from account.views import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', home_screen_view, name="home"),
    path('register/',registration_view,name="register"),
    path('logout/',logout_view,name="logout"),
    path('login/',login_view,name="login"),
    path('account/',account_view,name="account"),
    path('account/edit/',account_edit,name="edit"),
    path('account/saved/',account_saved,name="saved"),
    path('account/aboutus/',about_us_view,name="AboutUs"),
    path('monument/',include('monument.urls','monument')),
    path('routing/', include('routing.urls', namespace='routing')),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('must_admin/', must_admin_view, name="must_admin"),
    path('account/dashboard/', users_table_view, name="dashboard"),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/principal/models.py
from django.db import models

# Create your models here.

src/principal/views.py
from django.shortcuts import render, get_object_or_404
from monument.models import Monument
from monument.views import get_monument_queryset
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from operator import attrgetter

# Create your views here.

MONUMENTS_PER_PAGE = 6

def home_screen_view(request):
	context={}
	user = request.user
	
	# search feature
	query = ''
	if request.GET:
		query = request.GET.get('q','')
		context['query'] = str(query)

	context['user'] = user
	monuments = get_monument_queryset(query)

	#pagination feature
	page = request.GET.get('page',1)
	monuments_paginator = Paginator(monuments, MONUMENTS_PER_PAGE)

	try:
		monuments = monuments_paginator.page(page)
	except PageNotAnInteger :
		monuments = monuments_paginator.page(MONUMENTS_PER_PAGE)
	except EmptyPage :
		monuments = monuments_paginator.page(monuments_paginator.num_pages)

	context['monuments'] = monuments
	
	return render(request,"principal/home.html", context)

src/principal/templates/principal/home.html
{% extends 'base.html' %}
{% load static %}
{% block content%}

<style type="text/css">
	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
	.box-element{
		box-shadow:hsl(0, 0%, 80%) 0 0 16px;
		background-color: #fff;
		border-radius: 4px;
		padding: 10px;
	}

	.thumbnail{
		width: 100%;
		height: 300px;
		-webkit-box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
	    -moz-box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
	    box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
	}

</style>


<div class="container-fluid">
	<div class="row" >
		{% if monuments %}
			{% for monument in monuments %}
			<div class="col-lg-4 mb-4">
				<a href="{% url 'monument:detail' monument.slug %}">
				<img class="thumbnail" src="{{monument.imageURL}}"></a>
				<div class="box-element product">
					<h6><strong>{{monument.title}}</strong><p style="display: inline-block; float: right">Date: {{monument.year}}</p></h6>
					<hr>

					<p>{{ monument.description|slice:"0:110"}}...</p>
					<a class="btn btn-info" href="{% url 'monument:detail' monument.slug %}">More Details</a>
					{% if user.is_admin %}
					<a class="btn btn-warning" href="{% url 'monument:edit' monument.slug %}">Edit</a>
					<a class="btn btn-danger" href="{% url 'monument:delete' monument.slug %}">Delete</a>
					{% endif %}


				</div>
			</div>
			{% endfor %}
		{% else %}
			<div class="container">
				<h2 class="card-title">Pas de résultat</h2>
				<p class="card-text"> aucun monument ne matche le résultat : "{{query}}"</p>
			</div>
		{% endif %}


	</div>
	{% include 'monument/snippets/monument_pagination.html' with monuments=monuments %}
</div>

<script type="text/javascript">

</script>
{% endblock content%}